# this source code form is subject to the terms of the mozilla public 
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

## ------------------------------------------- Plugin Enable Properties
mosip.certify.integration.scan-base-package=io.mosip.certify.postgresdataprovider.integration
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.integration.data-provider-plugin=PostgresDataProviderPlugin
mosip.certify.plugin-mode=DataProvider
mosip.certify.identifier=${mosip.certify.domain.url}

## --------------------------------------------DataProvider specific Certify configuration 
mosip.certify.mock.authenticator.get-identity-url=http://mock-identity-system:8082/v1/mock-identity-system/identity
--------------------------------------------------- 
# set custom VC expiry, supports limited subset of ISO-8601 Duration format starting from days to seconds
# E.g. P21dT1h-2m3s for more information check javadoc of Duration.parse(String)
mosip.certify.data-provider-plugin.vc-expiry-duration=P730d

# Cache-Control max-age value for rendering templates
mosip.certify.rendering-template.cache-max-age-days=1

## ------------------------------------------- Plugin specific usecase properties ------------------------------------------------------------
# DID where all keys are hosted
mosip.certify.data-provider-plugin.did-url=did:web:hirekarma1.github.io:tempfiles:directory

# temporary workaround -> INJIWEB-1202
mosip.certify.data-provider-plugin.id-field-prefix-uri=https://mosip.io/credential/

# maps OpenID scope to the DB query string where :id is fetched from the token's "sub" field
mosip.certify.data-provider-plugin.postgres.scope-query-mapping={\
  'mosip_identity_vc_ldp': 'select * from school_data where student_id=:id'\
}

## ------------------------------------------- UseCase specific default overriding properties ------------------------------------------------------------
mosip.certify.identifier=${mosip.certify.domain.url}

# Display property for the issuer
mosip.certify.credential-config.issuer.display={\
  {\
    'name': 'Cadastro Ambiental Rural',\
    'locale': 'en'\
  }\
}
